### PR TITLE
Modify Funtofem Mphys Imports

### PR DESCRIPTION
**Pull request by sean-engelstad**
* We are cleaning up funtofem Cython and python files, including moving the `funtofem/mphys` folder into the `pyfuntofem` folder, see the PR https://github.com/smdogroup/funtofem/pull/183.
* The import of the `MeldBuilder` class would be changed from `from funtofem.mphys import MeldBuilder` to `from pyfuntofem import MeldBuilder`. Another option to import after this change would be `from pyfuntofem.interface.mphys import MeldBuilder`.

### CODE REVIEW

**Comment by sean-engelstad** [comment]
I made the requested change from @timryanb so that the imports from pyfuntofem will now be `from pyfuntofem.mphys import MeldBuilder`. I've also updated the imports in this PR appropriately.

**Comment by kejacobson** [comment]
Can you confirm that the [conda package]( https://github.com/sean-engelstad/mphys/blob/funtofem_import/.github/workflows/unit_tests_and_docs.yml#L64) will still be `funtofem` or do we need to change this to pyfuntofem as well?


Also, you'll need to retroactively [verify](https://github.com/OpenMDAO/mphys#signed-commits) your commits before we can merge this.

**Comment by sean-engelstad** [comment]
@kejacobson the conda package for funtofem currently puts the `funtofem` and `pyfuntofem` folders into the site-packages/python3.*/ directory of your anaconda envs library. As of right now you could import it with `from funtofem.mphys import MeldBuilder`. After this change, either way by installing through anaconda or the git repo manually, you will need to import with `from pyfuntofem.mphys import MeldBuilder`. Also, with this change, only the `pyfuntofem` folder will be put in the conda-python folder of your current environment.

**Comment by kejacobson** [comment]
I understand the file move and import change, but my question was: is the conda package name going to remain `funtofem` or are you going to change that to `pyfuntofem` as well? That is, will this line need to also be pyfuntofem:

```
mamba install -c "smdogroup/label/complex" -c smdogroup -c conda-forge tacs funtofem -q -y;
```

**Comment by sean-engelstad** [comment]
That's a good question. It kind of bothers me that the repo is called funtofem and the python package is `pyfuntofem`, but I think we'll leave it like that for now. Thus, the conda install command in the unit tests for `mphys` should remain the same.

**Comment by sean-engelstad** [comment]
@kejacobson, I talked with @bburke38 and we decided to change the PR to put all python and cython code into the `funtofem` folder so that way the python module matches the conda package and repo name. Otherwise it is confusing and could be problematic for new users. As a result, the `funtofem.mphys` imports will not be changed and this pull request is unnecessary now, so I'm going to close it.

**Pull request closed without merging**
