### PR TITLE
Add option to Scenarios to run in a different directory

### PR DESCRIPTION
**Pull request by kejacobson**

### CODE REVIEW

**Comment by kejacobson** [comment]
@friedenhe , here's an initial cut of handling the directory changes at the `Scenario` level. Each time you instantiate a scenario, you'd add `run_directory='{run_dir}'` to the constructor arguments. It handles the execution phase, but it doesn't propagate to the builders for initialization.

**Comment by friedenhe** [comment]
@kejacobson I tested the new run_directory feature with DAFoam and it worked well (both in serial and in parallel). The only thing I needed to change was the DAFoam builder. I had to add the `run_directory` option to the DAFoam builder to let it read/initialize things in the desired subfolder. So in the run script, we need to prescribe `run_directory` to both the builder and scenario classes. Anyway, it is working for my case. Thanks!

**Comment by kejacobson** [comment]
@friedenhe  great, thanks for checking!

**Comment by kejacobson** [comment]
Closing for a new PR since I've messed up the verified commit history

**Pull request closed without merging**
