### PR TITLE
Add method for user post scenario subsystem

### PR DESCRIPTION
**Pull request by kejacobson**

### CODE REVIEW

**Comment by timryanb** [comment]
@kejacobson, the CI seems to be hanging indefinitely. Any idea whats going on?

**Comment by kejacobson** [comment]
> @kejacobson, the CI seems to be hanging indefinitely. Any idea whats going on?

Not sure, but I'll need to push more commits to add docs for this feature. We'll see if it continues to occur.

**Comment by timryanb** [comment]
> > @kejacobson, the CI seems to be hanging indefinitely. Any idea whats going on?
> 
> Not sure, but I'll need to push more commits to add docs for this feature. We'll see if it continues to occur.

The last one ran for > 2.5 hrs before I manually killed it. I can let this one run though

**Review by timryanb — APPROVED** [review]
Looks good on my end.

Might be worth considering a version bump to 1.1.0 (maybe after PR #111) @kejacobson ?

**Pull request merged**
