### PR TITLE
Expanding mask converter

### PR DESCRIPTION
**Pull request by bernardopacini**
The mask converter was previously only usable in the following scenarios:

Masking: 1 input / 1 output
Unmasking: 1 input / 1 output

In some situations, it would be useful to be able to mask several outputs from the same input, and unmask several inputs into the same output. The updated behavior is:

Masking: 1 input / n outputs
Unmasking: n inputs / 1 output

I am using this in DAFoam to redirect specific information to different components and it works as expected. However, it may be helpful to add in a few more warning messages for edge cases if you think that would be worthwhile (for example, to help a user catch overlapping input masks that would overwrite each other).

### CODE REVIEW

**Comment by bernardopacini** [comment]
I am not sure what happened with the failed test... has anyone seen this error before?

**Comment by timryanb** [comment]
Don't worry about the test @bernardopacini. There's currently a known problem with the conda installer for petsc that's causing the test to fail. I believe I heard from @swryan, that changing `conda install ...` to `mamba install ...` fix this problem in the short term. So this may be a work around we want to consider @kejacobson.

**Comment by kejacobson** [comment]
We can talk about the conda/mambc petsc issue in the telecon today. 

@bernardopacini, Tim has a unit test for the original mask converter functionality. Can you add one for your multiple variable version?

**Review by timryanb — APPROVED** [review]

**Comment by kejacobson** [comment]
Bernardo, since Tim approved the changes and petsc conda issue doesn't look to be resolved, you can try Tim's suggestion of `mamba install` [here](https://github.com/OpenMDAO/mphys/blob/main/.github/workflows/unit_tests_and_docs.yml#L49) and [here](https://github.com/OpenMDAO/mphys/blob/main/.github/workflows/host_docs.yml#L44).

**Comment by swryan** [comment]
> Bernardo, since Tim approved the changes and petsc conda issue doesn't look to be resolved, you can try Tim's suggestion of `mamba install` [here](https://github.com/OpenMDAO/mphys/blob/main/.github/workflows/unit_tests_and_docs.yml#L49) and [here](https://github.com/OpenMDAO/mphys/blob/main/.github/workflows/host_docs.yml#L44).

For reference..   the PR that should fix the conda issue is [here](https://github.com/conda/conda/pull/11612).
In the OpenMDAO workflow, we used `setup-miniconda` to install `mamba` which you can see [here](https://github.com/OpenMDAO/OpenMDAO/blob/master/.github/workflows/openmdao_test_workflow.yml)
```
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.PY }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true)
```

**Comment by minrk** [comment]
petsc metadata issue should be fixed now.

**Comment by timryanb** [comment]
As @minrk says, the problem seems to be resolved now and the CI is working again. Think we can go ahead and merge as-is

**Pull request merged**
